package io.pilots.processservice.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.flowable.engine.HistoryService;
import org.flowable.engine.RuntimeService;
import org.flowable.engine.TaskService;
import org.flowable.engine.history.HistoricProcessInstance;
import org.flowable.engine.history.HistoricProcessInstanceQuery;
import org.flowable.engine.runtime.Execution;
import org.flowable.engine.runtime.ExecutionQuery;
import org.flowable.engine.runtime.ProcessInstance;
import org.flowable.engine.runtime.ProcessInstanceQuery;
import org.flowable.task.api.Task;
import org.flowable.task.api.TaskQuery;
import org.flowable.variable.api.history.HistoricVariableInstance;
import org.flowable.variable.api.history.HistoricVariableInstanceQuery;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
import org.springframework.boot.autoconfigure.security.servlet.SecurityFilterAutoConfiguration;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.hamcrest.Matchers.matchesPattern;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(
        value = ServiceInstanceController.class,
        excludeAutoConfiguration = {SecurityAutoConfiguration.class, SecurityFilterAutoConfiguration.class}
)
class ServiceInstanceControllerTest {

    // Lowercase UUID regex (UUID.toString() always emits lowercase hex)
    private static final String UUID_REGEX =
            "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";

    @Autowired
    MockMvc mockMvc;

    @Autowired
    ObjectMapper objectMapper;

    @MockBean
    RuntimeService runtimeService;

    @MockBean
    TaskService taskService;

    @MockBean
    HistoryService historyService;

    // -------------------------------------------------------------------------
    // POST /serviceInstances
    // -------------------------------------------------------------------------

    @Test
    void createServiceInstance_returns201_withUuidIdAndStartedState() throws Exception {
        // Flowable returns an internal process instance with a numeric ID.
        // The public UUID is generated by the controller and used as businessKey.
        ProcessInstance mockPi = mock(ProcessInstance.class);
        when(mockPi.getId()).thenReturn("2501");

        when(runtimeService.startProcessInstanceByKey(anyString(), anyString(), anyMap()))
                .thenReturn(mockPi);

        mockMvc.perform(post("/serviceInstances")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "serviceDefinition": "urn:example:process",
                                  "stakeholders": [
                                    {"role": "customer", "party": "did:web:example.com"}
                                  ],
                                  "parameters": {"orderId": "123"}
                                }
                                """))
                .andExpect(status().isCreated())
                // Location header must point to the newly created resource by UUID
                .andExpect(header().string("Location",
                        matchesPattern(".*/serviceInstances/" + UUID_REGEX)))
                // Response body must echo a valid UUID as id
                .andExpect(jsonPath("$.id", matchesPattern(UUID_REGEX)))
                .andExpect(jsonPath("$.serviceDefinition").value("urn:example:process"))
                // Default state when none is supplied in the request
                .andExpect(jsonPath("$.state").value("STARTED"))
                .andExpect(jsonPath("$.version").value(1));
    }

    // -------------------------------------------------------------------------
    // PATCH /serviceInstances/{serviceInstanceId}
    // -------------------------------------------------------------------------

    @Test
    void patchServiceInstance_invokesSetVariablesAndCompleteTask_returns200() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "2501";

        // --- Process-instance query chain ---
        ProcessInstance mockPi = mock(ProcessInstance.class);
        when(mockPi.getId()).thenReturn(flowableId);
        when(mockPi.getProcessDefinitionKey()).thenReturn("urn:example:process");

        ProcessInstanceQuery mockPiQuery = mock(ProcessInstanceQuery.class);
        when(runtimeService.createProcessInstanceQuery()).thenReturn(mockPiQuery);
        when(mockPiQuery.processInstanceBusinessKey(instanceId.toString())).thenReturn(mockPiQuery);
        when(mockPiQuery.singleResult()).thenReturn(mockPi);

        // Variables (including _version=1 for ETag check)
        when(runtimeService.getVariables(flowableId))
                .thenReturn(Map.of("orderId", "123", "_version", 1, "_state", "STARTED", "_stakeholders", "[]"));

        // --- Task query chain ---
        Task mockTask = mock(Task.class);
        when(mockTask.getId()).thenReturn("task-001");

        TaskQuery mockTaskQuery = mock(TaskQuery.class);
        when(taskService.createTaskQuery()).thenReturn(mockTaskQuery);
        when(mockTaskQuery.processInstanceId(flowableId)).thenReturn(mockTaskQuery);
        when(mockTaskQuery.singleResult()).thenReturn(mockTask);

        mockMvc.perform(patch("/serviceInstances/" + instanceId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("If-Match", "\"1\"")
                        .content("""
                                {
                                  "parameters": {"status": "approved"},
                                  "state": "APPROVED"
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(instanceId.toString()))
                .andExpect(jsonPath("$.state").value("APPROVED"))
                .andExpect(jsonPath("$.version").value(2));

        // setVariables must be called exactly once with the Flowable process ID
        verify(runtimeService, times(1)).setVariables(eq(flowableId), anyMap());
        // The active task must be completed to advance the process
        verify(taskService, times(1)).complete("task-001");
    }

    @Test
    void patchServiceInstance_triggersReceiveTask_whenNoUserTaskFound_returns200() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "2501";

        // --- Process-instance query chain ---
        ProcessInstance mockPi = mock(ProcessInstance.class);
        when(mockPi.getId()).thenReturn(flowableId);
        when(mockPi.getProcessDefinitionKey()).thenReturn("urn:example:process");

        ProcessInstanceQuery mockPiQuery = mock(ProcessInstanceQuery.class);
        when(runtimeService.createProcessInstanceQuery()).thenReturn(mockPiQuery);
        when(mockPiQuery.processInstanceBusinessKey(instanceId.toString())).thenReturn(mockPiQuery);
        when(mockPiQuery.singleResult()).thenReturn(mockPi);

        when(runtimeService.getVariables(flowableId)).thenReturn(Map.of());

        // --- No user task (process is at a receiveTask) ---
        TaskQuery mockTaskQuery = mock(TaskQuery.class);
        when(taskService.createTaskQuery()).thenReturn(mockTaskQuery);
        when(mockTaskQuery.processInstanceId(flowableId)).thenReturn(mockTaskQuery);
        when(mockTaskQuery.singleResult()).thenReturn(null);

        // --- Execution query chain (receiveTask waiting execution) ---
        Execution mockExecution = mock(Execution.class);
        when(mockExecution.getId()).thenReturn("exec-001");

        ExecutionQuery mockExecQuery = mock(ExecutionQuery.class);
        when(runtimeService.createExecutionQuery()).thenReturn(mockExecQuery);
        when(mockExecQuery.processInstanceId(flowableId)).thenReturn(mockExecQuery);
        when(mockExecQuery.onlyChildExecutions()).thenReturn(mockExecQuery);
        when(mockExecQuery.singleResult()).thenReturn(mockExecution);

        mockMvc.perform(patch("/serviceInstances/" + instanceId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("If-Match", "\"1\"")
                        .content("""
                                {"state": "COMPLETED"}
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(instanceId.toString()))
                .andExpect(jsonPath("$.state").value("COMPLETED"));

        // receiveTask must be resumed via runtimeService.trigger, not taskService.complete
        verify(runtimeService, times(1)).trigger("exec-001");
        verify(taskService, never()).complete(anyString());
    }

    @Test
    void patchServiceInstance_returns428_whenIfMatchHeaderAbsent() throws Exception {
        UUID instanceId = UUID.randomUUID();

        mockMvc.perform(patch("/serviceInstances/" + instanceId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"state\": \"APPROVED\"}"))
                .andExpect(status().isPreconditionRequired());
    }

    @Test
    void patchServiceInstance_returns412_whenIfMatchMismatch() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "2502";

        ProcessInstance mockPi = mock(ProcessInstance.class);
        when(mockPi.getId()).thenReturn(flowableId);
        when(mockPi.getProcessDefinitionKey()).thenReturn("urn:example:process");

        ProcessInstanceQuery mockPiQuery = mock(ProcessInstanceQuery.class);
        when(runtimeService.createProcessInstanceQuery()).thenReturn(mockPiQuery);
        when(mockPiQuery.processInstanceBusinessKey(instanceId.toString())).thenReturn(mockPiQuery);
        when(mockPiQuery.singleResult()).thenReturn(mockPi);

        when(runtimeService.getVariables(flowableId)).thenReturn(Map.of("_version", 1));

        mockMvc.perform(patch("/serviceInstances/" + instanceId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("If-Match", "\"99\"")
                        .content("{\"state\": \"APPROVED\"}"))
                .andExpect(status().isPreconditionFailed());
    }

    // -------------------------------------------------------------------------
    // GET /serviceInstances/{serviceInstanceId}
    // -------------------------------------------------------------------------

    @Test
    void getServiceInstance_returnsActiveInstance_returns200() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "2501";

        ProcessInstance mockPi = mock(ProcessInstance.class);
        when(mockPi.getId()).thenReturn(flowableId);
        when(mockPi.getProcessDefinitionKey()).thenReturn("urn:example:process");

        ProcessInstanceQuery mockPiQuery = mock(ProcessInstanceQuery.class);
        when(runtimeService.createProcessInstanceQuery()).thenReturn(mockPiQuery);
        when(mockPiQuery.processInstanceBusinessKey(instanceId.toString())).thenReturn(mockPiQuery);
        when(mockPiQuery.singleResult()).thenReturn(mockPi);

        when(runtimeService.getVariables(flowableId)).thenReturn(
                Map.of("_state", "STARTED", "_stakeholders", "[]", "orderId", "42"));

        mockMvc.perform(get("/serviceInstances/" + instanceId))
                .andExpect(status().isOk())
                .andExpect(header().exists("ETag"))
                .andExpect(jsonPath("$.id").value(instanceId.toString()))
                .andExpect(jsonPath("$.state").value("STARTED"))
                .andExpect(jsonPath("$.serviceDefinition").value("urn:example:process"))
                .andExpect(jsonPath("$.parameters.orderId").value("42"));
    }

    @Test
    void getServiceInstance_returnsCompletedInstance_fromHistory_returns200() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "2501";

        // No active process instance
        ProcessInstanceQuery mockPiQuery = mock(ProcessInstanceQuery.class);
        when(runtimeService.createProcessInstanceQuery()).thenReturn(mockPiQuery);
        when(mockPiQuery.processInstanceBusinessKey(instanceId.toString())).thenReturn(mockPiQuery);
        when(mockPiQuery.singleResult()).thenReturn(null);

        // Historic process instance
        HistoricProcessInstance mockHpi = mock(HistoricProcessInstance.class);
        when(mockHpi.getId()).thenReturn(flowableId);
        when(mockHpi.getProcessDefinitionKey()).thenReturn("urn:example:process");

        HistoricProcessInstanceQuery mockHpiQuery = mock(HistoricProcessInstanceQuery.class);
        when(historyService.createHistoricProcessInstanceQuery()).thenReturn(mockHpiQuery);
        when(mockHpiQuery.processInstanceBusinessKey(instanceId.toString())).thenReturn(mockHpiQuery);
        when(mockHpiQuery.singleResult()).thenReturn(mockHpi);

        // Historic variables
        HistoricVariableInstance stateVar = mock(HistoricVariableInstance.class);
        when(stateVar.getVariableName()).thenReturn("_state");
        when(stateVar.getValue()).thenReturn("COMPLETED");

        HistoricVariableInstance stakeholdersVar = mock(HistoricVariableInstance.class);
        when(stakeholdersVar.getVariableName()).thenReturn("_stakeholders");
        when(stakeholdersVar.getValue()).thenReturn("[]");

        HistoricVariableInstanceQuery mockVarQuery = mock(HistoricVariableInstanceQuery.class);
        when(historyService.createHistoricVariableInstanceQuery()).thenReturn(mockVarQuery);
        when(mockVarQuery.processInstanceId(flowableId)).thenReturn(mockVarQuery);
        when(mockVarQuery.list()).thenReturn(List.of(stateVar, stakeholdersVar));

        mockMvc.perform(get("/serviceInstances/" + instanceId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(instanceId.toString()))
                .andExpect(jsonPath("$.state").value("COMPLETED"))
                .andExpect(jsonPath("$.serviceDefinition").value("urn:example:process"));
    }

    @Test
    void getServiceInstance_returns404_whenNotFound() throws Exception {
        UUID instanceId = UUID.randomUUID();

        ProcessInstanceQuery mockPiQuery = mock(ProcessInstanceQuery.class);
        when(runtimeService.createProcessInstanceQuery()).thenReturn(mockPiQuery);
        when(mockPiQuery.processInstanceBusinessKey(instanceId.toString())).thenReturn(mockPiQuery);
        when(mockPiQuery.singleResult()).thenReturn(null);

        HistoricProcessInstanceQuery mockHpiQuery = mock(HistoricProcessInstanceQuery.class);
        when(historyService.createHistoricProcessInstanceQuery()).thenReturn(mockHpiQuery);
        when(mockHpiQuery.processInstanceBusinessKey(instanceId.toString())).thenReturn(mockHpiQuery);
        when(mockHpiQuery.singleResult()).thenReturn(null);

        mockMvc.perform(get("/serviceInstances/" + instanceId))
                .andExpect(status().isNotFound());
    }

    // -------------------------------------------------------------------------
    // GET /serviceInstances (list)
    // -------------------------------------------------------------------------

    /** Builds the mock chain for historyService.createHistoricProcessInstanceQuery() used by list. */
    private HistoricProcessInstanceQuery mockListQuery(List<HistoricProcessInstance> results) {
        HistoricProcessInstanceQuery q = mock(HistoricProcessInstanceQuery.class);
        when(historyService.createHistoricProcessInstanceQuery()).thenReturn(q);
        when(q.orderByProcessInstanceStartTime()).thenReturn(q);
        when(q.asc()).thenReturn(q);
        when(q.processDefinitionKey(anyString())).thenReturn(q);
        when(q.startedAfter(any())).thenReturn(q);
        when(q.startedBefore(any())).thenReturn(q);
        when(q.list()).thenReturn(results);
        return q;
    }

    @Test
    void listServiceInstances_returnsActiveInstance_returns200() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "3001";

        HistoricProcessInstance mockHpi = mock(HistoricProcessInstance.class);
        when(mockHpi.getId()).thenReturn(flowableId);
        when(mockHpi.getBusinessKey()).thenReturn(instanceId.toString());
        when(mockHpi.getProcessDefinitionKey()).thenReturn("urn:example:process");
        when(mockHpi.getEndTime()).thenReturn(null); // still active
        when(mockHpi.getStartTime()).thenReturn(null);

        mockListQuery(List.of(mockHpi));
        when(runtimeService.getVariables(flowableId))
                .thenReturn(Map.of("_state", "STARTED", "_stakeholders", "[]", "orderId", "42"));

        mockMvc.perform(get("/serviceInstances"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.items[0].id").value(instanceId.toString()))
                .andExpect(jsonPath("$.items[0].state").value("STARTED"))
                .andExpect(jsonPath("$.items[0].parameters.orderId").value("42"))
                .andExpect(jsonPath("$.count").value(1))
                .andExpect(jsonPath("$.total").value(1))
                .andExpect(jsonPath("$.limit").value(50))
                .andExpect(jsonPath("$.offset").value(0));
    }

    @Test
    void listServiceInstances_filtersByState_excludesNonMatching() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "3002";

        HistoricProcessInstance mockHpi = mock(HistoricProcessInstance.class);
        when(mockHpi.getId()).thenReturn(flowableId);
        when(mockHpi.getBusinessKey()).thenReturn(instanceId.toString());
        when(mockHpi.getProcessDefinitionKey()).thenReturn("urn:example:process");
        when(mockHpi.getEndTime()).thenReturn(null);
        when(mockHpi.getStartTime()).thenReturn(null);

        mockListQuery(List.of(mockHpi));
        when(runtimeService.getVariables(flowableId))
                .thenReturn(Map.of("_state", "STARTED", "_stakeholders", "[]"));

        // Filter for COMPLETED — no items should be returned
        mockMvc.perform(get("/serviceInstances").param("state", "COMPLETED"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.items").isEmpty())
                .andExpect(jsonPath("$.total").value(0));
    }

    @Test
    void listServiceInstances_respectsPagination() throws Exception {
        // Two instances; request offset=1, limit=1 → only second one returned
        UUID id1 = UUID.randomUUID();
        UUID id2 = UUID.randomUUID();

        HistoricProcessInstance hpi1 = mock(HistoricProcessInstance.class);
        when(hpi1.getId()).thenReturn("4001");
        when(hpi1.getBusinessKey()).thenReturn(id1.toString());
        when(hpi1.getProcessDefinitionKey()).thenReturn("urn:example:process");
        when(hpi1.getEndTime()).thenReturn(null);
        when(hpi1.getStartTime()).thenReturn(null);

        HistoricProcessInstance hpi2 = mock(HistoricProcessInstance.class);
        when(hpi2.getId()).thenReturn("4002");
        when(hpi2.getBusinessKey()).thenReturn(id2.toString());
        when(hpi2.getProcessDefinitionKey()).thenReturn("urn:example:process");
        when(hpi2.getEndTime()).thenReturn(null);
        when(hpi2.getStartTime()).thenReturn(null);

        mockListQuery(List.of(hpi1, hpi2));
        when(runtimeService.getVariables("4001")).thenReturn(Map.of("_state", "STARTED", "_stakeholders", "[]"));
        when(runtimeService.getVariables("4002")).thenReturn(Map.of("_state", "STARTED", "_stakeholders", "[]"));

        mockMvc.perform(get("/serviceInstances")
                        .param("limit", "1")
                        .param("offset", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.items.length()").value(1))
                .andExpect(jsonPath("$.items[0].id").value(id2.toString()))
                .andExpect(jsonPath("$.count").value(1))
                .andExpect(jsonPath("$.total").value(2))
                .andExpect(jsonPath("$.limit").value(1))
                .andExpect(jsonPath("$.offset").value(1));
    }

    // -------------------------------------------------------------------------
    // DELETE /serviceInstances/{serviceInstanceId}
    // -------------------------------------------------------------------------

    private ProcessInstanceQuery mockPiQueryReturning(UUID instanceId, ProcessInstance pi) {
        ProcessInstanceQuery q = mock(ProcessInstanceQuery.class);
        when(runtimeService.createProcessInstanceQuery()).thenReturn(q);
        when(q.processInstanceBusinessKey(instanceId.toString())).thenReturn(q);
        when(q.singleResult()).thenReturn(pi);
        return q;
    }

    @Test
    void deleteServiceInstance_returns204_onSuccess() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "5001";

        ProcessInstance mockPi = mock(ProcessInstance.class);
        when(mockPi.getId()).thenReturn(flowableId);
        mockPiQueryReturning(instanceId, mockPi);
        when(runtimeService.getVariables(flowableId)).thenReturn(Map.of("_version", 1));

        mockMvc.perform(delete("/serviceInstances/" + instanceId)
                        .header("If-Match", "\"1\""))
                .andExpect(status().isNoContent());

        verify(runtimeService, times(1)).deleteProcessInstance(flowableId, "Deleted via API");
    }

    @Test
    void deleteServiceInstance_returns404_whenNotFound() throws Exception {
        UUID instanceId = UUID.randomUUID();
        mockPiQueryReturning(instanceId, null);

        mockMvc.perform(delete("/serviceInstances/" + instanceId)
                        .header("If-Match", "\"1\""))
                .andExpect(status().isNotFound());
    }

    @Test
    void deleteServiceInstance_returns412_whenETagMismatch() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "5002";

        ProcessInstance mockPi = mock(ProcessInstance.class);
        when(mockPi.getId()).thenReturn(flowableId);
        mockPiQueryReturning(instanceId, mockPi);
        when(runtimeService.getVariables(flowableId)).thenReturn(Map.of("_version", 1));

        mockMvc.perform(delete("/serviceInstances/" + instanceId)
                        .header("If-Match", "\"42\""))
                .andExpect(status().isPreconditionFailed());

        verify(runtimeService, never()).deleteProcessInstance(anyString(), anyString());
    }

    // -------------------------------------------------------------------------
    // PUT /serviceInstances/{serviceInstanceId}
    // -------------------------------------------------------------------------

    @Test
    void replaceServiceInstance_returns200_andIncrementsVersion() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "6001";

        ProcessInstance mockPi = mock(ProcessInstance.class);
        when(mockPi.getId()).thenReturn(flowableId);
        when(mockPi.getProcessDefinitionKey()).thenReturn("urn:example:process");
        mockPiQueryReturning(instanceId, mockPi);

        // Current vars: one old parameter (orderId) that will be replaced
        when(runtimeService.getVariables(flowableId))
                .thenReturn(Map.of("_version", 1, "_state", "STARTED", "_stakeholders", "[]", "orderId", "old"));

        // No active user task
        TaskQuery mockTaskQuery = mock(TaskQuery.class);
        when(taskService.createTaskQuery()).thenReturn(mockTaskQuery);
        when(mockTaskQuery.processInstanceId(flowableId)).thenReturn(mockTaskQuery);
        when(mockTaskQuery.singleResult()).thenReturn(null);

        ExecutionQuery mockExecQuery = mock(ExecutionQuery.class);
        when(runtimeService.createExecutionQuery()).thenReturn(mockExecQuery);
        when(mockExecQuery.processInstanceId(flowableId)).thenReturn(mockExecQuery);
        when(mockExecQuery.onlyChildExecutions()).thenReturn(mockExecQuery);
        when(mockExecQuery.singleResult()).thenReturn(null);

        mockMvc.perform(put("/serviceInstances/" + instanceId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("If-Match", "\"1\"")
                        .content("""
                                {
                                  "serviceDefinition": "urn:example:process",
                                  "stakeholders": [{"role": "customer", "party": "did:web:example.com"}],
                                  "parameters": {"newParam": "value"},
                                  "state": "ACTIVE"
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(instanceId.toString()))
                .andExpect(jsonPath("$.version").value(2))
                .andExpect(jsonPath("$.state").value("ACTIVE"))
                .andExpect(jsonPath("$.parameters.newParam").value("value"));

        // Old parameter key (orderId) must be removed; new variables set
        verify(runtimeService, times(1)).removeVariables(eq(flowableId), argThat(c -> c.contains("orderId")));
        verify(runtimeService, times(1)).setVariables(eq(flowableId), anyMap());
    }

    @Test
    void replaceServiceInstance_returns412_whenETagMismatch() throws Exception {
        UUID instanceId = UUID.randomUUID();
        String flowableId = "6002";

        ProcessInstance mockPi = mock(ProcessInstance.class);
        when(mockPi.getId()).thenReturn(flowableId);
        when(mockPi.getProcessDefinitionKey()).thenReturn("urn:example:process");
        mockPiQueryReturning(instanceId, mockPi);
        when(runtimeService.getVariables(flowableId)).thenReturn(Map.of("_version", 1));

        mockMvc.perform(put("/serviceInstances/" + instanceId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("If-Match", "\"5\"")
                        .content("""
                                {
                                  "serviceDefinition": "urn:example:process",
                                  "stakeholders": [],
                                  "state": "ACTIVE"
                                }
                                """))
                .andExpect(status().isPreconditionFailed());
    }
}
